// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdpiopuoqmfmoxypafcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcGlvcHVvcW1mbW94eXBhZmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDQ1NzUsImV4cCI6MjA2MDYyMDU3NX0.41j-LGcusGD-skqrCWJGZQ-goYleOgYxcoM1gryoEc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);